GPS = gpsSensor( ...
    'HorizontalPositionAccuracy',1, ...
    'VerticalPositionAccuracy',2, ...
    'DecayFactor',0.95, ...
    'UpdateRate',5, ...
    'ReferenceLocation',[uav.ic.gsLL uav.ic.gsH]);

figure(2)
clf
hold on
for x = 0:5:120
    pos = GPS(single([0 0 0]), single([0 0 0]));
    plot (x,pos(3), '*');
end
hold off

